create database notas2023PHP;
use notas2023PHP;
create table USUARIOS(
ID_USUARIOS INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOMBREUSU VARCHAR(60) NOT NULL,
APELLIDOUSU VARCHAR (60) NOT NULL,
USUARIO VARCHAR (40) NOT NULL UNIQUE,
PASSWORDU VARCHAR (80) NOT NULL,
PERFIL VARCHAR (30) NOT NULL,
ESTADO VARCHAR (20) NOT NULL);

CREATE TABLE MATERIAS(
ID_MATERIA INT (15) auto_increment NOT NULL primary KEY,
MATERIA VARCHAR (30) NOT NULL);

CREATE TABLE ESTUDIANTES(
ID_ESTUDIANTE INT(15) AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOMBREE VARCHAR (60) NOT NULL,
APELLIDOE VARCHAR (60) NOT NULL,
DOCUMENTOE VARCHAR (12) NOT NULL,
CORREOE VARCHAR (60) NOT NULL,
MATERIAE VARCHAR (30) NOT NULL,
DOCENTE VARCHAR (60) NOT NULL,
PROMEDIO INT (3) NOT NULL,
FECHA_REGISTRO DATE);

CREATE TABLE DOCENTES(
ID_DOCENTE INT(15) NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRED VARCHAR(60) NOT NULL,
APELLIDOD VARCHAR (60) NOT NULL,
DOCUMENTOD VARCHAR (12) NOT NULL,
CORREOD VARCHAR (40) NOT NULL,
MATERIAD VARCHAR (30) NOT NULL,
NOTADS DECIMAL(5,1) NOT NULL);

CREATE TABLE NOTAS_ESTUDIANTE(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_ESTUDIANTESS INT (15) NOT NULL,
ID_MATERIASS INT (15) NOT NULL,
ID_DOCENTESS INT (15) NOT NULL,
PUNTAJE DECIMAL (5,1) NOT NULL,
FOREIGN KEY (ID_ESTUDIANTESS) REFERENCES ESTUDIANTES(ID_ESTUDIANTE) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ID_MATERIASS) REFERENCES MATERIAS(ID_MATERIA) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ID_DOCENTESS) REFERENCES DOCENTES(ID_DOCENTE) ON DELETE CASCADE ON UPDATE CASCADE);